### ISSUE TITLE
[Feature] Activate discussions on github and redirect FAQ to discussions github

### ISSUE THREAD

**Issue by louchebem06** [d-r-e/rncp#28]

**Comment by d-r-e** [comment]
Discussions are up! 😄

I meant the FAQ area to explain RNCP and what it means for students, since many students from Spanish campuses have had problems getting to understand the french title and its equivalence to our education system.

However it would be nice to have a link to Discussions or somewhere to talk about ideas, features or anything. Feel free to add it!

**Comment by axelcoezard** [comment]
We could add a "Discussions"/"Forum" link into the footer of the page, next to the github link
